apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rag-nov6-4-v-gitops
  description: This is GitOps manifest for rag-nov6-4-v   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: rag-nov6-4-v
    janus-idp.io/tekton: rag-nov6-4-v 
    backstage.io/kubernetes-id: rag-nov6-4-v 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rag-nov6-4-v
