kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rag-nov6-4-v-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: rag-nov6-4-v-dsp-job
    namespace: rag-nov6-4-v
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rag-nov6-4-v-imagestream-job-role
