apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: rag-nov6-4-v
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-nov6-4-v 
  name: rag-nov6-4-v
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rag-nov6-4-v 
    weight: 100 
  wildcardPolicy: None
