apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rag-nov6-4-v
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-nov6-4-v 
  name: rag-nov6-4-v
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: rag-nov6-4-v 
